language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn install --ignore-engines
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: dist/
  keep-history: true
  on:
    branch: master
  fqdn: texas.rzeszow.pl
